# Generated by Django 5.1.3 on 2024-12-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
